"""initial schema

Revision ID: 730e5b7a2104
Revises: 
Create Date: 2026-07-03 16:32:24.705886

"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa  # noqa: F401
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '730e5b7a2104'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('repo', 'service', 'user', 'team', 'pr', 'ticket', 'doc', 'adr', 'incident', 'api', 'db_table', 'context_packet', 'agent_run', name='entity_type', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('external_ref', sa.String(length=300), nullable=True),
    sa.Column('entity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'name', name='uq_entities_type_name')
    )
    op.create_table('eval_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('expected_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('github', 'jira', 'slack', 'confluence', 'adr', 'incident', 'ci', 'feedback', name='source_type', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_status', sa.Enum('idle', 'syncing', 'ok', 'error', name='sync_status', native_enum=False, length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('acl_sync_status', sa.Enum('ok', 'pending', 'error', name='acl_sync_status', native_enum=False, length=32), nullable=False),
    sa.Column('authority_rank', sa.Integer(), nullable=False),
    sa.Column('freshness_window_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('owns', 'member_of', 'authored', 'references', 'modifies', 'resolves', 'caused_by', 'depends_on', 'documents', 'cites', 'deployed_in', 'used_by', name='edge_type', native_enum=False, length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('edge_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'type', name='uq_edges_source_target_type')
    )
    op.create_index('ix_edges_source_entity_id', 'edges', ['source_entity_id'], unique=False)
    op.create_index('ix_edges_target_entity_id', 'edges', ['target_entity_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'lead', 'engineer', 'viewer', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_color', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('repo', sa.String(length=200), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.Enum('commit', 'pr', 'review', 'doc_edit', 'ticket', 'incident', 'packet_use', name='activity_event_type', native_enum=False, length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repo', 'service', 'event_type', 'day', name='uq_activity_events_cell')
    )
    op.create_index('ix_activity_events_day', 'activity_events', ['day'], unique=False)
    op.create_index('ix_activity_events_user_id', 'activity_events', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('api', 'mcp', name='api_key_kind', native_enum=False, length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=300), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='conflict_status', native_enum=False, length=32), nullable=False),
    sa.Column('recommended_document_id', sa.Uuid(), nullable=True),
    sa.Column('affected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_adr_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_packets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('bugfix', 'feature', 'refactor', 'incident_response', 'question', 'unknown', name='intent', native_enum=False, length=32), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('compiled_context', sa.Text(), nullable=False),
    sa.Column('selected_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejected_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflict_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acl_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_outcome', sa.Enum('pending', 'succeeded', 'failed', 'abandoned', name='agent_outcome', native_enum=False, length=32), nullable=False),
    sa.Column('feedback_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.Enum('code', 'pr', 'ticket', 'doc', 'message', 'adr', 'incident', 'ci_run', 'feedback', name='doc_type', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('repo', sa.String(length=200), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'stale', 'deprecated', name='doc_status', native_enum=False, length=32), nullable=False),
    sa.Column('topic_key', sa.String(length=200), nullable=True),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('acl_public', sa.Boolean(), nullable=False),
    sa.Column('acl_team_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acl_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_documents_source_external')
    )
    op.create_index('ix_documents_doc_type', 'documents', ['doc_type'], unique=False)
    op.create_index('ix_documents_repo', 'documents', ['repo'], unique=False)
    op.create_index('ix_documents_service', 'documents', ['service'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_topic_key', 'documents', ['topic_key'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('baseline', 'context_engine', 'comparison', name='eval_mode', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='eval_run_status', native_enum=False, length=32), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=200), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='agent_run_status', native_enum=False, length=32), nullable=False),
    sa.Column('context_packet_id', sa.Uuid(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('changed_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_output', sa.Text(), nullable=True),
    sa.Column('pr_url', sa.String(length=1000), nullable=True),
    sa.Column('reviewer_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('langfuse_trace_id', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_packet_id'], ['context_packets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('eval_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eval_run_id', sa.Uuid(), nullable=False),
    sa.Column('eval_task_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('baseline', 'context_engine', name='eval_result_mode', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['eval_task_id'], ['eval_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('context_packet_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('useful', 'irrelevant', 'missing_context', 'stale_context', 'permission_issue', 'suggest_source', 'promote_authoritative', 'mark_deprecated', name='feedback_type', native_enum=False, length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_packet_id'], ['context_packets.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('eval_results')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunks_document_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('agent_runs')
    op.drop_table('eval_runs')
    op.drop_index('ix_documents_topic_key', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_service', table_name='documents')
    op.drop_index('ix_documents_repo', table_name='documents')
    op.drop_index('ix_documents_doc_type', table_name='documents')
    op.drop_table('documents')
    op.drop_table('context_packets')
    op.drop_table('conflicts')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('api_keys')
    op.drop_index('ix_activity_events_user_id', table_name='activity_events')
    op.drop_index('ix_activity_events_day', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_table('users')
    op.drop_index('ix_edges_target_entity_id', table_name='edges')
    op.drop_index('ix_edges_source_entity_id', table_name='edges')
    op.drop_table('edges')
    op.drop_table('teams')
    op.drop_table('sources')
    op.drop_table('eval_tasks')
    op.drop_table('entities')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
